package com.quovex.domain.usecase

import com.quovex.data.remote.dto.AiSummaryResult
import com.quovex.data.remote.dto.ChatMessageDto
import com.quovex.data.remote.dto.GeneratedFlashcardDto
import com.quovex.domain.model.DomainImageInput
import com.quovex.domain.model.ImageDoubtSolution
import com.quovex.domain.model.QuizQuestion
import com.quovex.domain.model.SubjectInference
import com.quovex.domain.repository.AIRepository

class FakeAIRepository : AIRepository {

    var summarizeResult: Result<AiSummaryResult> = Result.success(
        AiSummaryResult(
            summary = "Structured summary generated by AI.",
            keyPoints = listOf("Point 1: Key formula", "Point 2: Core principle"),
            flashcards = listOf(
                GeneratedFlashcardDto(question = "What is F?", answer = "Mass times acceleration", formula = "F=ma")
            )
        )
    )

    var imageDoubtResult: Result<ImageDoubtSolution> = Result.success(
        ImageDoubtSolution(
            solution = "Step 1: Identify given quantities.\nStep 2: Apply Newton's Second Law.\nAnswer: a = 5 m/s^2",
            provider = "groq",
            model = "openai/gpt-oss-120b"
        )
    )

    var urlExtractResult: Result<Pair<String, String>> = Result.success(
        Pair("Photosynthesis Overview", "Photosynthesis is a biological process used by plants to convert light energy.")
    )

    var classifyResult: Result<SubjectInference> = Result.success(
        SubjectInference(
            subject = "Physics",
            topic = "Newton's Laws of Motion",
            subtopic = "Laws of Motion",
            examRelevance = listOf("JEE", "NEET"),
            confidence = 0.95f
        )
    )

    var quizResult: Result<List<QuizQuestion>> = Result.success(
        listOf(
            QuizQuestion(
                id = 1,
                materialId = 0,
                question = "What is F in F=ma?",
                options = listOf("Force", "Frequency", "Friction", "Flux"),
                correctIndex = 0,
                explanation = "F stands for Force.",
                relatedConcept = "Newton's Second Law"
            )
        )
    )

    var shouldFailSummarize: Boolean = false
    var shouldFailDoubt: Boolean = false
    var shouldFailUrl: Boolean = false
    var shouldFailClassify: Boolean = false
    var shouldFailQuiz: Boolean = false

    override suspend fun sendChatMessage(
        message: String,
        subject: String,
        history: List<ChatMessageDto>
    ): Result<String> = Result.success("Echo: $message")

    override suspend fun sendTutorMessage(
        message: String,
        subject: String,
        topic: String,
        materialSummary: String?,
        recentMistakes: List<String>,
        history: List<ChatMessageDto>
    ): Result<String> = Result.success("Tutor response for $subject: $message")

    override suspend fun classifyMaterial(
        textSample: String,
        filename: String?
    ): Result<SubjectInference> {
        if (shouldFailClassify) return Result.failure(Exception("Classification failed"))
        return classifyResult
    }

    override suspend fun summarizeNote(
        rawText: String,
        subject: String
    ): Result<AiSummaryResult> {
        if (shouldFailSummarize) return Result.failure(Exception("AI Gateway Summarization error"))
        return summarizeResult
    }

    override suspend fun generateQuiz(
        subject: String,
        topic: String,
        difficulty: String,
        keyPoints: List<String>
    ): Result<List<QuizQuestion>> {
        if (shouldFailQuiz) return Result.failure(Exception("Quiz generation failed"))
        return quizResult
    }

    override suspend fun solveImageDoubt(
        imageInput: DomainImageInput,
        subject: String,
        questionText: String
    ): Result<ImageDoubtSolution> {
        if (shouldFailDoubt) return Result.failure(Exception("Vision AI Provider unavailable"))
        return imageDoubtResult
    }

    override suspend fun extractUrlContent(url: String): Result<Pair<String, String>> {
        if (shouldFailUrl) return Result.failure(Exception("Failed to fetch web content from URL"))
        return urlExtractResult
    }

    override suspend fun generateStudyPlan(
        examName: String,
        targetHours: Int,
        subjects: List<String>,
        days: Int
    ): Result<String> = Result.success("Sample Study Plan")

    override suspend fun getDailyQuote(streak: Int): Result<Pair<String, String>> =
        Result.success(Pair("Study hard", "Author"))
}
