export interface NcertBook {
  id: string;
  bookCode: string;
  title: string;
  classLevel: number;
  gradeClass: string;
  subject: string;
  language: string;
  curriculum: string;
  publisher: string;
  contentType: 'OFFICIAL_RESOURCE';
  edition: string;
  totalChapters: number;
}

export interface NcertChapter {
  id: string;
  bookId: string;
  bookCode: string;
  bookTitle: string;
  chapterNumber: number;
  chapterTitle: string;
  classLevel: number;
  gradeClass: string;
  subject: string;
  officialSourceUrl: string;
  language: string;
  curriculum: string;
  publisher: string;
  contentType: 'OFFICIAL_RESOURCE';
  keyConcepts: string[];
  sampleFormulas?: string[];
  summaryOutline: string;
}

export const NCERT_CATALOG: {
  version: number;
  lastUpdated: string;
  curriculum: string;
  publisher: string;
  books: NcertBook[];
  chapters: NcertChapter[];
} = {
  version: 2,
  lastUpdated: '2026-08-29',
  curriculum: 'CBSE / NCERT Rationalised Edition',
  publisher: 'NCERT',
  books: [
    // Class 6
    {
      id: 'ncert-6-sci',
      bookCode: 'fesc1',
      title: 'Science (Curiosity)',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 11,
    },
    {
      id: 'ncert-6-math',
      bookCode: 'femh1',
      title: 'Mathematics (Ganita Prakash)',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 12,
    },
    // Class 7
    {
      id: 'ncert-7-sci',
      bookCode: 'gesc1',
      title: 'Science',
      classLevel: 7,
      gradeClass: 'Class 7',
      subject: 'Science',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
    {
      id: 'ncert-7-math',
      bookCode: 'gemh1',
      title: 'Mathematics',
      classLevel: 7,
      gradeClass: 'Class 7',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
    // Class 8
    {
      id: 'ncert-8-sci',
      bookCode: 'hesc1',
      title: 'Science',
      classLevel: 8,
      gradeClass: 'Class 8',
      subject: 'Science',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
    {
      id: 'ncert-8-math',
      bookCode: 'hemh1',
      title: 'Mathematics',
      classLevel: 8,
      gradeClass: 'Class 8',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
    // Class 9
    {
      id: 'ncert-9-sci',
      bookCode: 'iesc1',
      title: 'Science',
      classLevel: 9,
      gradeClass: 'Class 9',
      subject: 'Science',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 12,
    },
    {
      id: 'ncert-9-math',
      bookCode: 'iemh1',
      title: 'Mathematics',
      classLevel: 9,
      gradeClass: 'Class 9',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 12,
    },
    // Class 10
    {
      id: 'ncert-10-sci',
      bookCode: 'jesc1',
      title: 'Science',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Science',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
    {
      id: 'ncert-10-math',
      bookCode: 'jemh1',
      title: 'Mathematics',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 14,
    },
    // Class 11
    {
      id: 'ncert-11-phy-1',
      bookCode: 'keph1',
      title: 'Physics Part I',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Physics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 7,
    },
    {
      id: 'ncert-11-phy-2',
      bookCode: 'keph2',
      title: 'Physics Part II',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Physics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 7,
    },
    {
      id: 'ncert-11-chem-1',
      bookCode: 'kech1',
      title: 'Chemistry Part I',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Chemistry',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 6,
    },
    {
      id: 'ncert-11-chem-2',
      bookCode: 'kech2',
      title: 'Chemistry Part II',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Chemistry',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 3,
    },
    {
      id: 'ncert-11-math',
      bookCode: 'kemh1',
      title: 'Mathematics',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 14,
    },
    {
      id: 'ncert-11-bio',
      bookCode: 'kebo1',
      title: 'Biology',
      classLevel: 11,
      gradeClass: 'Class 11',
      subject: 'Biology',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 19,
    },
    // Class 12
    {
      id: 'ncert-12-phy-1',
      bookCode: 'leph1',
      title: 'Physics Part I',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 8,
    },
    {
      id: 'ncert-12-phy-2',
      bookCode: 'leph2',
      title: 'Physics Part II',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 6,
    },
    {
      id: 'ncert-12-chem-1',
      bookCode: 'lech1',
      title: 'Chemistry Part I',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Chemistry',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 5,
    },
    {
      id: 'ncert-12-chem-2',
      bookCode: 'lech2',
      title: 'Chemistry Part II',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Chemistry',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 5,
    },
    {
      id: 'ncert-12-math-1',
      bookCode: 'lemh1',
      title: 'Mathematics Part I',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 6,
    },
    {
      id: 'ncert-12-math-2',
      bookCode: 'lemh2',
      title: 'Mathematics Part II',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Mathematics',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 7,
    },
    {
      id: 'ncert-12-bio',
      bookCode: 'lebo1',
      title: 'Biology',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Biology',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      edition: 'Rationalised Edition',
      totalChapters: 13,
    },
  ],
  chapters: [
    // ──────── Class 6 Science (Curiosity) ────────
    {
      id: 'ncert-6-sci-ch1',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 1,
      chapterTitle: 'Components of Food',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=1-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Nutrients', 'Carbohydrates', 'Proteins', 'Fats', 'Vitamins', 'Balanced Diet', 'Deficiency Diseases'],
      summaryOutline: 'Nutritional requirements of the human body, tests for starch, proteins, and fats, and identifying deficiency disorders such as scurvy, rickets, and beriberi.',
    },
    {
      id: 'ncert-6-sci-ch2',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 2,
      chapterTitle: 'Sorting Materials into Groups',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=2-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Lustre', 'Hardness', 'Solubility', 'Density (Float/Sink)', 'Transparency (Opaque, Translucent, Transparent)'],
      summaryOutline: 'Classification of objects based on physical properties including appearance, hardness, solubility in water, and optical transparency.',
    },
    {
      id: 'ncert-6-sci-ch3',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 3,
      chapterTitle: 'Separation of Substances',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=3-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Handpicking', 'Threshing', 'Winnowing', 'Sieving', 'Sedimentation & Decantation', 'Filtration', 'Evaporation'],
      summaryOutline: 'Methods of separating solid-solid and solid-liquid mixtures utilizing differences in particle size, density, and boiling points.',
    },
    {
      id: 'ncert-6-sci-ch4',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 4,
      chapterTitle: 'Getting to Know Plants',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=4-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Herbs, Shrubs, Trees', 'Stem & Venation', 'Leaf Structure (Transpiration, Photosynthesis)', 'Roots (Tap & Fibrous)', 'Flower Anatomy (Petals, Sepals, Stamens, Pistil)'],
      summaryOutline: 'Morphology of plants, internal anatomy of leaves and stems, and the functional anatomy of flowers.',
    },
    {
      id: 'ncert-6-sci-ch5',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 5,
      chapterTitle: 'Body Movements',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=5-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Ball and Socket Joint', 'Pivotal Joint', 'Hinge Joint', 'Fixed Joints', 'Human Skeleton', 'Gait of Animals'],
      summaryOutline: 'Joint mechanisms in the human musculoskeletal system and locomotion in earthworms, snails, cockroaches, and birds.',
    },
    {
      id: 'ncert-6-sci-ch6',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 6,
      chapterTitle: 'The Living Organisms — Characteristics and Habitats',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=6-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Biotic & Abiotic Components', 'Terrestrial & Aquatic Habitats', 'Adaptations (Desert, Mountain, Marine)', 'Excretion & Respiration'],
      summaryOutline: 'Ecosystem components, anatomical and behavioral adaptations of flora and fauna across desert, mountain, and aquatic biomes.',
    },
    {
      id: 'ncert-6-sci-ch7',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 7,
      chapterTitle: 'Motion and Measurement of Distances',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=7-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['SI Units (Metre)', 'Rectilinear Motion', 'Circular Motion', 'Periodic Motion', 'Measurement Parallax Error'],
      sampleFormulas: ['1\\text{ km} = 1000\\text{ m}', '1\\text{ m} = 100\\text{ cm}'],
      summaryOutline: 'Standard metric measurement units, precautions against parallax error, and classifying motion as rectilinear, circular, or periodic.',
    },
    {
      id: 'ncert-6-sci-ch8',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 8,
      chapterTitle: 'Light, Shadows and Reflections',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=8-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Rectilinear Propagation of Light', 'Shadow Formation', 'Pinhole Camera', 'Plane Mirrors & Reflection'],
      summaryOutline: 'Light travels in straight lines, pinhole camera inverted image formation, and law of specular reflection from plane surfaces.',
    },
    {
      id: 'ncert-6-sci-ch9',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 9,
      chapterTitle: 'Electricity and Circuits',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=9-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Electric Cell (Terminals)', 'Closed vs Open Circuit', 'Electric Switch', 'Conductors vs Insulators'],
      summaryOutline: 'Structure of dry electric cells, current path in complete closed circuits, and classification of conductors vs insulators.',
    },
    {
      id: 'ncert-6-sci-ch10',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 10,
      chapterTitle: 'Fun with Magnets',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=10-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Magnetic vs Non-Magnetic Materials', 'Magnetic Poles (North & South)', 'Law of Magnetic Poles (Attraction & Repulsion)', 'Magnetic Compass'],
      summaryOutline: 'Discovery of lodestone/magnetite, magnetic pole polarity, making temporary magnets, and directional navigational compasses.',
    },
    {
      id: 'ncert-6-sci-ch11',
      bookId: 'ncert-6-sci',
      bookCode: 'fesc1',
      bookTitle: 'Science (Curiosity)',
      chapterNumber: 11,
      chapterTitle: 'Air Around Us',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?fesc1=11-11',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Atmosphere', 'Composition of Air (Nitrogen 78%, Oxygen 21%, CO2, Water Vapour)', 'Oxygen Cycle & Photosynthesis', 'Wind Energy'],
      summaryOutline: 'Atmospheric layers, gaseous composition of air, supporting combustion and aquatic respiration, and ecological oxygen-carbon dioxide balance.',
    },

    // ──────── Class 6 Mathematics ────────
    {
      id: 'ncert-6-math-ch1',
      bookId: 'ncert-6-math',
      bookCode: 'femh1',
      bookTitle: 'Mathematics (Ganita Prakash)',
      chapterNumber: 1,
      chapterTitle: 'Knowing Our Numbers',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Mathematics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?femh1=1-12',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Indian & International Place Value System', 'Estimation & Rounding Off', 'BODMAS Brackets', 'Roman Numerals'],
      sampleFormulas: ['\\text{Crore} = 10^7', '\\text{Million} = 10^6'],
      summaryOutline: 'Large numbers comparison, commas placement in Indian and International systems, estimation to nearest tens/hundreds, and Roman numeral rules.',
    },
    {
      id: 'ncert-6-math-ch2',
      bookId: 'ncert-6-math',
      bookCode: 'femh1',
      bookTitle: 'Mathematics (Ganita Prakash)',
      chapterNumber: 2,
      chapterTitle: 'Whole Numbers',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Mathematics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?femh1=2-12',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Predecessor & Successor', 'Number Line Representation', 'Closure Property', 'Commutativity & Associativity', 'Distributivity of Multiplication over Addition'],
      sampleFormulas: ['a(b + c) = ab + ac', 'a + 0 = a'],
      summaryOutline: 'Natural numbers vs whole numbers, number line operations, and fundamental arithmetic axioms on whole numbers.',
    },
    {
      id: 'ncert-6-math-ch3',
      bookId: 'ncert-6-math',
      bookCode: 'femh1',
      bookTitle: 'Mathematics (Ganita Prakash)',
      chapterNumber: 3,
      chapterTitle: 'Playing with Numbers',
      classLevel: 6,
      gradeClass: 'Class 6',
      subject: 'Mathematics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?femh1=3-12',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Factors & Multiples', 'Prime & Composite Numbers', 'Divisibility Tests (2, 3, 4, 5, 6, 8, 9, 10, 11)', 'Highest Common Factor (HCF)', 'Lowest Common Multiple (LCM)'],
      sampleFormulas: ['\\text{HCF}(a, b) \\times \\text{LCM}(a, b) = a \\times b'],
      summaryOutline: 'Prime factorization by ladder method, Sieve of Eratosthenes, divisibility rules, and solving practical HCF/LCM word problems.',
    },

    // ──────── Class 10 Science ────────
    {
      id: 'ncert-10-sci-ch1',
      bookId: 'ncert-10-sci',
      bookCode: 'jesc1',
      bookTitle: 'Science',
      chapterNumber: 1,
      chapterTitle: 'Chemical Reactions and Equations',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=1-13',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Law of Conservation of Mass', 'Balancing Equations', 'Combination & Decomposition Reactions', 'Displacement & Double Displacement', 'Oxidation, Reduction, Redox', 'Corrosion & Rancidity'],
      sampleFormulas: ['\\text{CaO} + \\text{H}_2\\text{O} \\rightarrow \\text{Ca(OH)}_2 + \\Delta H'],
      summaryOutline: 'Stoichiometric balancing of chemical equations, thermal/photolytic/electrolytic decomposition, displacement reactions based on reactivity series, and redox mechanisms.',
    },
    {
      id: 'ncert-10-sci-ch2',
      bookId: 'ncert-10-sci',
      bookCode: 'jesc1',
      bookTitle: 'Science',
      chapterNumber: 2,
      chapterTitle: 'Acids, Bases and Salts',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=2-13',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Indicators & Olfactory Indicators', 'Acid-Base Reactions with Metals', 'pH Scale & Hydrogen Ion Concentration', 'Chlor-Alkali Process (NaOH, Cl2, H2)', 'Bleaching Powder, Baking Soda, Washing Soda, Plaster of Paris'],
      sampleFormulas: ['\\text{pH} = -\\log[\\text{H}^+]', '\\text{CaSO}_4\\cdot\\frac{1}{2}\\text{H}_2\\text{O} + 1\\frac{1}{2}\\text{H}_2\\text{O} \\rightarrow \\text{CaSO}_4\\cdot2\\text{H}_2\\text{O}'],
      summaryOutline: 'Neutralization equilibria, pH importance in everyday physiology and agriculture, and industrial preparation of sodium compounds and gypsum/POP.',
    },
    {
      id: 'ncert-10-sci-ch10',
      bookId: 'ncert-10-sci',
      bookCode: 'jesc1',
      bookTitle: 'Science',
      chapterNumber: 10,
      chapterTitle: 'Light – Reflection and Refraction',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=10-13',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Spherical Mirrors (Concave & Convex)', 'Mirror Formula & Magnification', 'Snell\'s Law of Refraction', 'Refractive Index', 'Lens Formula & Power of Lens'],
      sampleFormulas: ['\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}', 'n = \\frac{c}{v}', '\\frac{1}{f} = \\frac{1}{v} - \\frac{1}{u}', 'P = \\frac{1}{f(\\text{m})}'],
      summaryOutline: 'Geometric ray optics for spherical mirrors and thin lenses, Cartesian sign conventions, refractive indices calculation, and optical power determination in dioptres.',
    },
    {
      id: 'ncert-10-sci-ch12',
      bookId: 'ncert-10-sci',
      bookCode: 'jesc1',
      bookTitle: 'Science',
      chapterNumber: 12,
      chapterTitle: 'Electricity',
      classLevel: 10,
      gradeClass: 'Class 10',
      subject: 'Science',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?jesc1=12-13',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Electric Current & Potential Difference', 'Ohm\'s Law & Resistance ($R = \\rho L/A$)', 'Resistors in Series & Parallel', 'Joule\'s Law of Heating', 'Electric Power ($P = VI = I^2R = V^2/R$)'],
      sampleFormulas: ['V = I R', 'R_s = R_1 + R_2 + R_3', '\\frac{1}{R_p} = \\frac{1}{R_1} + \\frac{1}{R_2}', 'H = I^2 R t', 'P = V I'],
      summaryOutline: 'Electrical drift, Ohm\'s law verification, resistivity temperature factors, equivalent resistance in networks, and commercial units of electrical energy ($1\\text{ kWh} = 3.6\\times 10^6\\text{ J}$).',
    },

    // ──────── Class 12 Physics Part I ────────
    {
      id: 'ncert-12-phy-1-ch1',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 1,
      chapterTitle: 'Electric Charges and Fields',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=1-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Coulomb\'s Law', 'Electric Field Intensity', 'Electric Dipole & Torque', 'Gauss\'s Law & Gaussian Surfaces', 'Field of Infinite Line & Sheet of Charge'],
      sampleFormulas: ['\\vec{F} = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1 q_2}{r^2}\\hat{r}', '\\oint \\vec{E}\\cdot d\\vec{A} = \\frac{q_{\\text{enclosed}}}{\\varepsilon_0}', 'E_{\\text{sheet}} = \\frac{\\sigma}{2\\varepsilon_0}'],
      summaryOutline: 'Electrostatic force quantisation and vector formulation, flux through closed surfaces via Gauss\'s Law, and derivation of field configurations for spherical shells, planes, and infinite wires.',
    },
    {
      id: 'ncert-12-phy-1-ch2',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 2,
      chapterTitle: 'Electrostatic Potential and Capacitance',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=2-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Electrostatic Potential & Potential Energy', 'Equipotential Surfaces', 'Parallel Plate Capacitor', 'Dielectrics & Polarisation', 'Energy Stored in Capacitor ($U = \\frac{1}{2}CV^2$)'],
      sampleFormulas: ['V = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q}{r}', 'C = \\frac{\\kappa \\varepsilon_0 A}{d}', 'U = \\frac{1}{2} C V^2'],
      summaryOutline: 'Conservative electrostatic work, dipole potential, dielectric slab insertion dynamics, and electrostatic energy density $u = \\frac{1}{2}\\varepsilon_0 E^2$.',
    },
    {
      id: 'ncert-12-phy-1-ch3',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 3,
      chapterTitle: 'Current Electricity',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=3-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Drift Velocity & Mobility', 'Ohm\'s Law Microscopic Form ($j = \\sigma E$)', 'Temperature Dependence of Resistivity', 'EMF & Internal Resistance', 'Kirchhoff\'s Rules (KCL & KVL)', 'Wheatstone Bridge Condition'],
      sampleFormulas: ['I = n e A v_d', 'v_d = -\\frac{e E \\tau}{m}', '\\frac{P}{Q} = \\frac{R}{S}', 'V = \\mathcal{E} - I r'],
      summaryOutline: 'Microscopic charge carrier kinematics, cell grouping in series/parallel, multi-loop nodal Kirchhoff analysis, and balanced Wheatstone bridge null-deflection.',
    },
    {
      id: 'ncert-12-phy-1-ch4',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 4,
      chapterTitle: 'Moving Charges and Magnetism',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=4-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Lorentz Magnetic Force', 'Biot-Savart Law', 'Ampere\'s Circuital Law', 'Force between Parallel Currents (Definition of Ampere)', 'Torque on Current Loop & Moving Coil Galvanometer'],
      sampleFormulas: ['\\vec{F} = q(\\vec{E} + \\vec{v}\\times\\vec{B})', 'd\\vec{B} = \\frac{\\mu_0}{4\\pi}\\frac{I d\\vec{l}\\times\\hat{r}}{r^2}', '\\oint \\vec{B}\\cdot d\\vec{l} = \\mu_0 I_{\\text{enclosed}}'],
      summaryOutline: 'Helical trajectory of charged particles in magnetic fields, solenoid and toroid field proofs, magnetic dipole moment of loops, and conversion of galvanometer to ammeter/voltmeter.',
    },
    {
      id: 'ncert-12-phy-1-ch6',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 6,
      chapterTitle: 'Electromagnetic Induction',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=6-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['Magnetic Flux', 'Faraday\'s Laws of Induction', 'Lenz\'s Law & Energy Conservation', 'Motional EMF ($\\mathcal{E} = Bvl$)', 'Self & Mutual Inductance', 'AC Generator Principle'],
      sampleFormulas: ['\\mathcal{E} = -\\frac{d\\Phi_B}{dt}', '\\mathcal{E} = B v l', 'U_L = \\frac{1}{2} L I^2'],
      summaryOutline: 'Induction mechanisms, magnetic back-EMF, self-inductance of solenoids, eddy current damping, and sinusoidal voltage generation.',
    },
    {
      id: 'ncert-12-phy-1-ch7',
      bookId: 'ncert-12-phy-1',
      bookCode: 'leph1',
      bookTitle: 'Physics Part I',
      chapterNumber: 7,
      chapterTitle: 'Alternating Current',
      classLevel: 12,
      gradeClass: 'Class 12',
      subject: 'Physics',
      officialSourceUrl: 'https://ncert.nic.in/textbook.php?leph1=7-8',
      language: 'English',
      curriculum: 'CBSE / NCERT',
      publisher: 'NCERT',
      contentType: 'OFFICIAL_RESOURCE',
      keyConcepts: ['RMS vs Peak Current', 'Phasor Diagrams for L, C, R', 'Series LCR Resonance', 'Quality Factor ($Q$)', 'Power Factor ($\\cos\\phi$)', 'Transformer Efficiency & Turns Ratio'],
      sampleFormulas: ['I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}}', 'Z = \\sqrt{R^2 + (X_L - X_C)^2}', '\\omega_0 = \\frac{1}{\\sqrt{LC}}', 'P_{\\text{avg}} = V_{\\text{rms}} I_{\\text{rms}} \\cos\\phi'],
      summaryOutline: 'Impedance triangle analysis, resonant electrical oscillations, wattless current condition, and step-up/step-down transformer magnetic core losses.',
    },
  ],
};

/**
 * Validates and queries chapters strictly according to official metadata.
 * Prevents cross-class / cross-curriculum leakage.
 */
export function getAvailableClasses(): string[] {
  const classes = Array.from(new Set(NCERT_CATALOG.books.map((b) => b.gradeClass)));
  return classes.sort((a, b) => {
    const numA = parseInt(a.replace(/\D/g, ''), 10);
    const numB = parseInt(b.replace(/\D/g, ''), 10);
    return numB - numA; // Class 12 down to Class 6
  });
}

export function getSubjectsForClass(gradeClass: string): string[] {
  const books = NCERT_CATALOG.books.filter((b) => b.gradeClass === gradeClass);
  return Array.from(new Set(books.map((b) => b.subject)));
}

export function getBooksForClassAndSubject(gradeClass: string, subject: string): NcertBook[] {
  return NCERT_CATALOG.books.filter(
    (b) => b.gradeClass === gradeClass && b.subject === subject
  );
}

export function getChaptersForClassAndSubject(gradeClass: string, subject: string): NcertChapter[] {
  return NCERT_CATALOG.chapters.filter(
    (c) => c.gradeClass === gradeClass && c.subject === subject
  );
}

export function getChapterById(chapterId: string): NcertChapter | undefined {
  return NCERT_CATALOG.chapters.find((c) => c.id === chapterId);
}
